ISO = "bento/centos-7.9"
DOMAIN = ".mgnosov"
HOST_PREFIX = "vm"

servers = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ssh_host => "2222",
    :ssh_vm => "22",
    :http_host => "8081",
    :http_vm => "8081",
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disable: false
  servers.each do |machine|
    config.vm.define machine[:hostname]
      config.vm.box = ISO
      config.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      config.vm.network :forwarded_port, guest: machine[:http_vm], host: machine[:http_host]
      config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:machine]
      config.vm.provision "ansible" do |setup|
        setup.playbook = "../test_assessment/src/ansible/provision.yaml"
        setup.become = true
        setup.extra_vars = { ansible_user: 'vagrant' }
        end
      end
    end
  end
